unbind C-r
bind -n C-r source-file ~/.tmux.conf

set-option -g default-shell /usr/bin/tcsh

# TMUX keybind
set -g prefix M-f
bind -n C-n 'new-window'
bind -n M-w 'kill-window'
bind -n M-1 'select-window -t 1'
bind -n M-2 'select-window -t 2'
bind -n M-3 'select-window -t 3'
bind -n M-4 'select-window -t 4'
bind -n M-5 'select-window -t 5'

bind-key M-h split-window -h
bind-key M-v split-window -v
bind-key M-f kill-pane
bind-key c copy-mode
bind-key v paste-buffer -p
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right
unbind C-Up
unbind C-Left
unbind C-Right
unbind C-Down
# TMUX plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


#run '~/.tmux/plugins/tpm/tpm'

# TMUX Config
set-option -g allow-rename off
set -g mouse on
set -g base-index 1
set -g set-clipboard on
set-option -g renumber-windows on
set -g detach-on-destroy off

# TMUX customization
# set-option -g default-terminal 'screen-254color'
# set-option -g terminal-overrides ',xterm-256color:RGB'
set -g visual-activity off
set -g visual-silence off
set -g visual-bell off
setw -g monitor-activity off
set -g bell-action none

setw -g clock-mode-colour yellow
setw -g mode-style 'fg=black bg=red bold'

set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

set-option -g status-position top
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left '#S'
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M ' 
set -g status-right-length 50

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format '#I #[fg=red]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

set -g message-style 'fg=yellow bg=red bold'
